version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
  telegram:
    container_name: telegram
    build:
      context:
        ./telegram-bot
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env