#Application
application:
  bot-token: ${BOT_TOKEN}
  bot-username: ${BOT_USERNAME}
  bot-owner-id: ${BOT_OWNER_ID}
spring:
  profiles:
    active: ${PROFILE}
#Database
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

  #Liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml